import type { Metadata } from "next"
import { Poppins, Lato } from "next/font/google"
import "./globals.scss"
import { Providers } from "./GlobalRedux/provider"

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: "700",
})
const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} ${poppins.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
